eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8001/eureka/
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/clouddo_cms_dev?useUnicode=true&characterEncoding=utf8
    username: root
    password: mysql