#security:
#  basic:
#    enabled: false
server:
  port: 8005

spring:
  profiles:
    active: dev
  application:
    name: api-admin
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8

mybatis:
  mapper-locations: mapper/**Mapper.xml
  configuration:
      map-underscore-to-camel-case: true